### ISSUE TITLE
No way to open .jnlp files for Asus iKVM

### ISSUE THREAD

**Issue by Plaidstallion** [mablanco/docker-firefox-java-vnc#1]
I am unable to get this container to load the *.jnlp files the ASMB8-iKVM IPMI 2.0 module serves up for remote viewing. I have tried opening with /usr/bin/java and /usr/bin/javaws with no luck. 
![kvm-jnlp](https://user-images.githubusercontent.com/44079566/91616473-0c54e080-e986-11ea-893e-f652586f72fe.jpg)

**Comment by mablanco** [comment]
Hi. Could you try to press the "Browse" button and use this path: "/usr/lib/jvm/java-6-openjdk-amd64/bin/javaws" ? Let me know the result.

**Comment by Plaidstallion** [comment]
That worked wonderfully. Thanks for the support. Do you have any plans to make this container for ARM devices like the Raspberry Pi? I would really like to host something like this on a low power machine in my network that is always on.

**Comment by mablanco** [comment]
Glad it worked. I've just uploaded a new image version (mablanco/firefox-java-vnc:20200830) that fixes the javaws association (the default for the icedtea-netx package is to point to OpenJDK 7, which is not installed) and links it to /usr/bin/javaws. So this is now the (shorter) path you can use now. It'd be great to also make Firefox use this as its default for JNLP but I don't know how to do it from the CLI.

Regarding ARM, it looks a good idea, but I don't have an ARM platform available right now to do this work. I think it could be possible, as the first Raspbian version was based on Debian Wheezy (as my image), but this needs further investigation.

**Comment by satomama** [comment]
same for me here I have also tried java 6 but get this error
![image](https://user-images.githubusercontent.com/16051679/171614593-0565e59f-4ae5-4d7d-b9c2-311e5c3d9f24.png)
would really appreciate some help on how to get ASMB8-iKVM (version 1.14) remote console to work

**Comment by mablanco** [comment]
Sorry but this issue was closed almost 2 years ago and your question is off-topic. I cannot give you support for a 3rd party tool I know nothing about and has nothing to do with my work.
